# -*- coding: utf-8 -*-
"""fake review detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jns_Uh1Bh3SkhdU08kOJUbcHdwOuQynL
"""

import pandas as pd
df = pd.read_csv('deceptive-opinion.csv')
print(df.head())

print(df['deceptive'].value_counts())
df['review_length'] = df['text'].apply(lambda x: len(x.split()))
print('DataFrame with new review_length column:')
print(df.head())

"""#TEXT PREPROCESSING"""

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)          # remove punctuation/numbers
    words = text.split()
    words = [lemmatizer.lemmatize(w) for w in words if w not in stop_words]
    return ' '.join(words)

df['clean_text'] = df['text'].apply(clean_text)

"""#TEXT TO BINARY"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TfidfVectorizer to convert text to weighted numerical values
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2))
X = tfidf.fit_transform(df['clean_text'])

# Corrected the target column name from 'label' to 'deceptive'
y = df['deceptive']

print(f'Feature matrix shape: {X.shape}')
print(f'Target labels shape: {y.shape}')

"""# Train/Test Split & Baseline Model"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

model = LogisticRegression()
model.fit(X_train, y_train)

from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix

params = {'C': [0.1, 1, 10]}
grid = GridSearchCV(LogisticRegression(max_iter=1000), params, cv=5, scoring='f1_macro')
grid.fit(X_train, y_train)

print(f'Best Parameters: {grid.best_params_}')

# Evaluate the best model
best_model = grid.best_estimator_
y_pred_best = best_model.predict(X_test)

print('\nFinal Model Evaluation (Best Estimator):')
print(classification_report(y_test, y_pred_best))

# Plotting the confusion matrix
cm = confusion_matrix(y_test, y_pred_best)
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=best_model.classes_, yticklabels=best_model.classes_)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - Best Logistic Regression')
plt.show()

"""### Test the Model with a Custom Review
You can edit the `custom_review` variable below to test any text you'd like.
"""

def predict_review(review_text):
    # 1. Clean the input text using the previously defined function
    cleaned = clean_text(review_text)

    # 2. Transform the text using the fitted TF-IDF vectorizer
    # Note: We use .transform(), NOT .fit_transform()
    vectorized = tfidf.transform([cleaned])

    # 3. Predict using the best model from GridSearchCV
    prediction = best_model.predict(vectorized)[0]

    # 4. Get probability scores
    probs = best_model.predict_proba(vectorized)[0]
    class_labels = best_model.classes_

    print(f'Review: "{review_text}"')
    print(f'Prediction: {prediction.upper()}')
    print(f'Confidence: {max(probs)*100:.2f}%')

# --- TEST IT HERE ---
custom_review = "ABSOLUTELY TERRIBLE!!!! DO NOT STAY HERE!!!! It was a total nightmare from start to finish!!!! The staff were so rude and the room was a complete disaster!!!! I have never been so disappointed in my entire life!!!! SAVE YOUR MONEY AND GO SOMEWHERE ELSE!!!! HORRIBLE!!!!!"
predict_review(custom_review)